# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mohamad Shehab
title: DevOps Architect
email: mohamadkhodorshehab@gmail.com
# email_title: Email (Email title override)
phone: 00971502158862
# phone_title: Phone (Phone title override)
website: mohamadshehab.net
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mhmdksh
github_username:  mhmdksh
linkedin_username: mohammad-khodor-shehab

additional_links:
- title: Book A Call
  icon: fa-cal.com (https://github.com/calcom/cal.com/blob/main/apps/web/public/favicon-32x32.png)
  url: https://cal.com/mohamadkhodorshehab

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/moe-thug.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, world! I'm Mohamad Shehab, a seasoned IT professional and a self-confessed automation addict. When I'm not busy managing the full spectrum of IT services and cloud solutions for multinational companies, you'll find me exploring the fascinating world of Web3.

  My journey in IT has been an exciting ride, from working on mission-critical systems to creating reliable cloud solutions. I'm a firm believer in the power of continuous learning, constantly leveling up my technical skills and XP points in the game of life.

  In the realm of DevOps, I'm a wizard, conjuring up solutions that enhance efficiency and reliability. My magic wand? My extensive IT administration and automation skills. But don't worry, I haven't forgotten the importance of soft skills in this digital age. I'm always working on those to ensure I'm not just a code-crunching machine, but also a human who values connections and teamwork.

  Ready to embark on a quest in the world of IT services and cloud solutions? Let's connect!

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: General Magic
        sub_title: Devops Specialist
        caption: March 2022 - present
        link: https://www.generalmagic.io
        quote: |
          Web3 professionals building social impact solutions throughout Web3 and Public Good space.
        description: | # this will include new lines to allow paragraphs
          - Developing and maintaining Impact DAO products, contributing to the creation of 1-click apps for communities.
          - Advising on product-as-a-service strategies, leading to monetization of Impact DAO products.
          - Implementing DevOps best practices to enhance scalability and security of various infrastructures.
          - Automating operational tasks, including server provision, management, and database orchestration.
          - Overseeing services for Giveth dApps, ensuring optimal performance and security.
          - Architecting microservices and Kubernetes infrastructure, and presenting plans to the development team.
          - Creating Infrastructure as Code (IaC) scripts for on-demand testing infrastructure.
          - Migrating services to Kubernetes for improved scalability and zero-downtime deployments.
          - Building CI/CD pipelines for automated testing, building, releasing, security scanning, and deployment of applications.
          - Establishing IT/DevOps processes for maintenance, backup/recovery, and monitoring.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: IDEMIA
        sub_title: IT Systems Analyst
        caption: April 2018 - February 2022
        link: https://www.idemia.com
        quote: >
          The leader in Identity Technologies, and Identity Management Systems
        description: | # this will include new lines to allow paragraphs
          - Participated in a DevOps team to integrate a scalable Kubernetes application, automating source code management, deployment, and monitoring for production environments.
          - Developed automated alerting channels in the CI/CD pipeline, enhancing team proactivity in incident management.
          - Analyzed system and application behavior to ensure alignment with business goals.
          - Conducted acceptance testing with various APIs integrated into the system to ensure functionality.
          - Provided feedback to development teams on application behavior, tracking issues, and requesting updates.
          - Automated administration procedures, reducing system management times by 90% and eliminating human error.
          - Collaborated with Networking, SRE, and Security teams to implement incident management procedures.
          - Ensured 99% uptime as per SLAs by delegating preventive maintenance tasks to the support team on sites.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Infosysta
        sub_title: IT Administrator & Infrastructure Owner
        caption: June 2016 - March 2018
        link: https://www.infosysta.com
        quote: >
          A Turn-key Management Consultant & Atlassian Strategic Partner
        description: | # this will include new lines to allow paragraphs
          - Managed a Cloud Infrastructure of over 30 servers for a SaaS Legal solution (App4Legal) with around 30,000 subscribers.
          - Developed an automated procedure integrated into the CI/CD pipeline, reducing application integration time from 3 days to 15 minutes and implementation cost by 90%.
          - Created containerized images for the application, enhancing testing efficiency for both the development team and clients.
          - Set up time-based monitoring and event-based alerting solutions, increasing visibility of application status and behavior.
          - Planned and executed on-premises-to-cloud & cloud-to-cloud migration procedures, reducing running costs and improving application scalability.
          - Automated cloud backup and restoration procedures using bash scripting and Ansible, aligning service with the company's RPO & RTO policy.
          - Developed a plug-n-play solution for testing the application on both on-premises and cloud infrastructure, reducing the barrier to entry for application use.
          - Mitigated cyber attacks and protected data, ensuring the security of our services.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: American University of Science & Technology
        sub_title: Information & Communication Technology
        caption: 2011 - 2016
        quote: >
          The American University of Science and Technology is a private, non-sectarian, and co-educational American university in Lebanon.
        description: | # this will include new lines to allow paragraphs
        
  - title: Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Skills
        additional_links:
          - title:  Kubernetes
            icon: fab fa-github (https://user-images.githubusercontent.com/25181517/182534006-037f08b5-8e7b-4e5f-96b6-5d2a5558fa85.png)
            url: https://www.credly.com/badges/85d7a85f-6d07-4a45-83e7-b8a7e160ff87/linked_i
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
