# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mohamad Shehab
title: Devops & Solutions Architect
email: mohamadkhodorshehab@gmail.com
# email_title: Email (Email title override)
phone: 00971502158862
# phone_title: Phone (Phone title override)
website: mohamadshehab.net
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mhmdksh
github_username:  mhmdksh
linkedin_username: mohammad-khodor-shehab

additional_links:
- title: Telegram
  icon: fa fa-telegram
  url: https://t.me/mhmdksh_93

- title: Book A Call
  icon: fas fa-calendar-alt
  url: https://cal.com/mohamadkhodorshehab

- title: Download Resume
  icon: fas fa-download
  url: https://drive.google.com/file/d/1ywjeQVoJ3WqWy_IoaRMR3hcg38mb_7zE/view?usp=drive_link

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/moe-thug.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Mohamad Shehab, an experienced IT professional specializing in DevOps, cloud architecture, and AI integration. With a proven track record of managing comprehensive IT services and cloud solutions for multinational organizations, I bring deep expertise in building scalable, reliable infrastructure and implementing cutting-edge AI solutions.

  Throughout my career, I have successfully delivered mission-critical systems, architected robust cloud infrastructures, and developed AI-powered tools that significantly enhance developer productivity and operational efficiency. My technical expertise spans from implementing Large Language Models (LLMs) and orchestrating complex cloud environments to creating automated workflows that transform business operations.

  As a DevOps practitioner, I excel at designing and implementing solutions that optimize performance, reliability, and scalability. My core competencies include infrastructure automation, CI/CD pipeline development, container orchestration, and cloud-native architecture. I am passionate about leveraging emerging technologies, particularly in the Web3 and AI domains, to drive innovation and create tangible business value.

  I am committed to continuous professional development and maintaining expertise at the forefront of technology trends. My approach combines strong technical capabilities with effective communication and collaborative leadership, ensuring successful project delivery and team alignment.

  I welcome opportunities to discuss how my expertise in IT services, AI solutions, and cloud infrastructure can contribute to your organization's success.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Rekt Studios
        sub_title: Solution Architect (Part Time)
        caption: April 2024 - Present
        link: https://rektstudios.com
        description: | # this will include new lines to allow paragraphs
          - Planning and implementing the AWS Cloud Infrastructure for a Blockchain Game Backend, using different services like ECS, ECR, Cloudfront, Route53, Secrets Manager, S3, RDS, SES
          - Creating a High Available IaC Setup using Terraform, to implement all the infrastructure, that brought the implementation time from Days to Minutes
          - Building the development and release process that contributed to having an efficient and automated SDLC
          - Training the Dev Team on the release process and making their work structured and efficient and less prone to faults
          - Automating the release process through CI-CD Pipelines using Github Actions
          - Implementing a Secret and ENV Management Solution using Hashicorps Vault which reduced human error while handling Secrets by 99%
          - Contributing to the Backend Development

      - layout: left
        title: General Magic
        sub_title: Devops Team Lead
        caption: March 2022 - present
        link: https://www.generalmagic.io
        quote: |
          Web3 professionals building social impact solutions throughout Web3 and Public Good space.
        description: | # this will include new lines to allow paragraphs
          - Developed an AI-powered Discord Bot using Python (LangChain) and OpenAI API that scans GitHub repositories, prioritizes issues, and updates Notion documentation automatically—enhancing developer workflow and team communication
          - Built a Web3 grant recommendation AI Agent (JavaScript, Twitter/Telegram APIs, ElizaOS) that identifies tailored funding opportunities, optimizing the grant application process
          - Developing and maintaining Impact DAO products, contributing to the creation of 1-click apps for communities.
          - Advising on product-as-a-service strategies, leading to monetization of Impact DAO products.
          - Implementing DevOps best practices to enhance scalability and security of various infrastructures.
          - Automating operational tasks, including server provision, management, and database orchestration.
          - Overseeing services for Giveth dApps, ensuring optimal performance and security.
          - Architecting microservices and Kubernetes infrastructure, and presenting plans to the development team.
          - Creating Infrastructure as Code (IaC) scripts for on-demand testing infrastructure.
          - Migrating services to Kubernetes for improved scalability and zero-downtime deployments.
          - Building CI/CD pipelines for automated testing, building, releasing, security scanning, and deployment of applications.
          - Establishing IT/DevOps processes for maintenance, backup/recovery, and monitoring.

      - layout: left
        title: IDEMIA
        sub_title: IT Systems Analyst
        caption: April 2018 - February 2022
        link: https://www.idemia.com
        quote: >
          The leader in Identity Technologies, and Identity Management Systems
        description: | # this will include new lines to allow paragraphs
          - Participated in a DevOps team to integrate a scalable Kubernetes application, automating source code management, deployment, and monitoring for production environments.
          - Developed automated alerting channels in the CI/CD pipeline, enhancing team proactivity in incident management.
          - Analyzed system and application behavior to ensure alignment with business goals.
          - Conducted acceptance testing with various APIs integrated into the system to ensure functionality.
          - Provided feedback to development teams on application behavior, tracking issues, and requesting updates.
          - Automated administration procedures, reducing system management times by 90% and eliminating human error.
          - Collaborated with Networking, SRE, and Security teams to implement incident management procedures.
          - Ensured 99% uptime as per SLAs by delegating preventive maintenance tasks to the support team on sites.

      - layout: left
        title: Infosysta
        sub_title: IT Administrator & Infrastructure Owner
        caption: June 2016 - March 2018
        link: https://www.infosysta.com
        quote: >
          A Turn-key Management Consultant & Atlassian Strategic Partner
        description: | # this will include new lines to allow paragraphs
          - Managed a Cloud Infrastructure of over 30 servers for a SaaS Legal solution (App4Legal) with around 30,000 subscribers.
          - Developed an automated procedure integrated into the CI/CD pipeline, reducing application integration time from 3 days to 15 minutes and implementation cost by 90%.
          - Created containerized images for the application, enhancing testing efficiency for both the development team and clients.
          - Set up time-based monitoring and event-based alerting solutions, increasing visibility of application status and behavior.
          - Planned and executed on-premises-to-cloud & cloud-to-cloud migration procedures, reducing running costs and improving application scalability.
          - Automated cloud backup and restoration procedures using bash scripting and Ansible, aligning service with the company's RPO & RTO policy.
          - Developed a plug-n-play solution for testing the application on both on-premises and cloud infrastructure, reducing the barrier to entry for application use.
          - Mitigated cyber attacks and protected data, ensuring the security of our services.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: American University of Science & Technology
        sub_title: Information & Communication Technology
        caption: 2011 - 2016
        quote: >
          The American University of Science and Technology is a private, non-sectarian, and co-educational American university in Lebanon.
        description: | # this will include new lines to allow paragraphs

  - title: Technical Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Skills
        additional_links:
          - title:  Kubernetes
            icon: kube (https://user-images.githubusercontent.com/25181517/182534006-037f08b5-8e7b-4e5f-96b6-5d2a5558fa85.png)
            url: https://www.credly.com/badges/85d7a85f-6d07-4a45-83e7-b8a7e160ff87/linked_i
        description: | # this will include new lines to allow paragraphs
          - <mark>AI Tools</mark>: LangChain, Eliza Framework 'AI Agents', Local LLMs
          - <mark>Programming/Scripting</mark>: JavaScript, Python, JAVA, BASH, BATCH, SQL, YAML
          - <mark>Container Management & Orchestration</mark>: Docker, Docker-Compose, Kubernetes, Helm, Nomad
          - <mark>CI/CD Piplines</mark>: GitHub Actions, TravisCI
          - <mark>Infrastructure as Code IaC & Configuration Management</mark>: Terraform, Ansible
          - <mark>Cloud</mark>: AWS, GCP, Azure, Digital Ocean, Linode, Vultr, Hetzner
          - <mark>Monitoring, Logging Tracing, Alerting</mark>: Grafana, Prometheus, Loki, Promtail, ELK Stack, Opentelemetry, Tempo
          - <mark>Web/DB Stacks</mark>: MySQL, Apache, Nginx, PHP, NodeJS, Tomcat, Caddy
          - <mark>Databases & OS</mark>: MySQL, Oracle, PostgreSQL, MongoDB, Windows, UNIX
          - <mark>IT Infrastructure Management</mark>: On-Premises & Cloud
          - <mark>Secret Management</mark>: Hashicorp Vault, AWS Secret Manager
          - <mark>WEB3 Tools</mark>: IPFS, Blockchain APIs (ETH, ETHL2), Vaults
          - <mark>DAO Tools</mark>: On-Chain Proposals, DAO Voting, Infrastructure Governance, Multisigs Wallet Governance (Gnosis Safe), DAO Management EVM Scripting, Tokenomics

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]