name: update-site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Update my Site
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.MOHAMADSHEHAB_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/mad-moe/git/my-resume
            git reset --hard main
            git pull origin main
            docker-compose up -d --force-recreate