name: update-site

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Staging deploy Giveth-All
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MOHAMADSHEHAB_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/mad-moe/git/my-resume
            docker-compose down
            git pull
            docker-compose up -d
